### ISSUE TITLE
FriendsActivity Zeile 72

### ISSUE THREAD

**Issue by DanielHilpoltsteiner** [Prof-Greipl/CHATMOBILE2014#1]
new GetFriendsTask().execute(null, null, null);
Der korrekte Aufruf wäre new GetFriendsTask().execute();
Die Anzahl der Parameter die übergeben werden spielt keine Rolle. (kann keins oder auch unendlich viele sein)
Außerdem ist im Task definiert, dass die Parameter vom Typ Void sind. Mit diesen wird auch später nicht gearbeitet. Es erweckt an der Stelle den Eindruck dass die Parameteranzahl denen in den <> des Tasks entsprechen müssen, was nicht richtig ist.

**Comment by dgreipl** [comment]
Danke. Korrekt.
